package adbm.git.ui;

import adbm.main.Main;
import adbm.util.EverythingIsNonnullByDefault;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.swing.*;
import java.awt.*;

@EverythingIsNonnullByDefault
public class AddBranchDialog extends JDialog
{
    private static final Logger log = LogManager.getLogger(AddBranchDialog.class);

    private JList<String> listAvailableBranches;
    private JPanel panel;
    private JButton buttonAddBranch;

    private static AddBranchDialog addBranchDialog;

    public static void showAddBranchDialog()
    {
        addBranchDialog = new AddBranchDialog();
        addBranchDialog.setVisible(true);
    }

    private AddBranchDialog()
    {
        super(GitDialog.getGitDialog(), "Add Branch", ModalityType.APPLICATION_MODAL);
        setContentPane(panel);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pack();
        setLocationRelativeTo(GitDialog.getGitDialog());
        DefaultListModel<String> listAvailableBranchesModel = new DefaultListModel<>();
        Main.getGitManager().getAllNonLocalRemoteBranches().forEach(listAvailableBranchesModel::addElement);
        listAvailableBranches.setModel(listAvailableBranchesModel);

        buttonAddBranch.addActionListener(e -> {
            if (listAvailableBranches.getSelectedValue() != null) {
                Main.getGitManager().checkoutBranch(listAvailableBranches.getSelectedValue());
                this.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(2, 1, new Insets(20, 20, 20, 20), -1, -1));
        buttonAddBranch = new JButton();
        buttonAddBranch.setText("Add Branch");
        panel.add(buttonAddBranch,
                  new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                      GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                      GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                   GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
                                                   GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW,
                                                   null, null, null, 0, false));
        listAvailableBranches = new JList();
        scrollPane1.setViewportView(listAvailableBranches);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel;
    }
}
