package adbm.resultsVisualization;

import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.ui.UIUtils;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class VisualizationPanel extends JPanel
{
    private JPanel panel;
    private JButton buttonSave;
    private JPanel panelChart;
    private JPanel readPanel;
    private JPanel updatePanel;
    JFrame frame = new JFrame("Results Visualization Window");
    ArrayList<JFreeChart> savedChartList = new ArrayList<JFreeChart>();;

    public VisualizationPanel (ChartPanel chartPanel) {

        frame.setContentPane(panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        UIUtils.centerFrameOnScreen(frame);
        frame.setVisible(true);

        buttonSave.addActionListener(e -> {
            VisualizationMain.convertToPdf(savedChartList,640,480);
        });
    }

    public void setReadPanel(ChartPanel chartPanel) {
        if(chartPanel == null) System.out.println("readPanel");
        else {
            VisualizationMain.readChart = chartPanel.getChart();
            readPanel.add(chartPanel, BorderLayout.CENTER);
            readPanel.updateUI();
            savedChartList.add(chartPanel.getChart());
        }
    }

    public void setUpdatePanel(ChartPanel chartPanel) {
        if (chartPanel == null) System.out.println("readPanel");
        else {
            VisualizationMain.updateChart = chartPanel.getChart();
            updatePanel.add(chartPanel, BorderLayout.CENTER);
            updatePanel.updateUI();
            savedChartList.add(chartPanel.getChart());
        }
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel;
    }

}